// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyGy5CNxAVhImykuHacpUsy_tmQ8E5rX8',
    appId: '1:489504347963:web:f99dd734d315d82fc7c91e',
    messagingSenderId: '489504347963',
    projectId: 'chknotify45',
    authDomain: 'chknotify45.firebaseapp.com',
    storageBucket: 'chknotify45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLYQLV2mN6YEN88T2WpVhdcuGNoCFaWnw',
    appId: '1:489504347963:android:d65ac0227dc5addbc7c91e',
    messagingSenderId: '489504347963',
    projectId: 'chknotify45',
    storageBucket: 'chknotify45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAihCOROG6I5JFCavTKIv_EDzVR7VscgZY',
    appId: '1:489504347963:ios:e32694217de8411ac7c91e',
    messagingSenderId: '489504347963',
    projectId: 'chknotify45',
    storageBucket: 'chknotify45.firebasestorage.app',
    iosBundleId: 'com.example.chkNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAihCOROG6I5JFCavTKIv_EDzVR7VscgZY',
    appId: '1:489504347963:ios:e32694217de8411ac7c91e',
    messagingSenderId: '489504347963',
    projectId: 'chknotify45',
    storageBucket: 'chknotify45.firebasestorage.app',
    iosBundleId: 'com.example.chkNotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyGy5CNxAVhImykuHacpUsy_tmQ8E5rX8',
    appId: '1:489504347963:web:6988c6e6c693b573c7c91e',
    messagingSenderId: '489504347963',
    projectId: 'chknotify45',
    authDomain: 'chknotify45.firebaseapp.com',
    storageBucket: 'chknotify45.firebasestorage.app',
  );
}
